services:

  postgres:
    image: postgres:18.0
    environment:
      - POSTGRES_USER=fet_db_user
      - POSTGRES_PASSWORD=lksdo24!^0'234
      - POSTGRES_DB=fet_local_db
    ports:
      - "54321:5432"