from typing import Protocol
from uuid import UUID
from src.domain.expense import model as expense_model


class IUserRepository(Protocol):
    def has_role(self, user_id: UUID, role: str) -> bool: ...

    def is_same_organization(self, user_id: UUID, org_id: UUID) -> bool: ...

    def exists(self, user_id: UUID) -> bool: ...


class IExpenseRepository(Protocol):
    def get(self, expense_id: UUID) -> expense_model.Expense: ...

    def save(self, expense: expense_model.Expense) -> None: ...

    def find_by_organization(self, org_id: UUID) -> list[expense_model.Expense]: ...
